// SPDX-License-Identifier: Apache-2.0
import { build } from "esbuild";
import { mkdir, writeFile, copyFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const destination = path.resolve(here, "../../Sources/CellApple/Resources/haven-localization.js");
const result = await build({
  entryPoints: [path.join(here, "runtime.mjs")],
  bundle: true, format: "iife", globalName: "HavenLocalization", target: "es2020",
  minify: true, legalComments: "inline", write: false,
  banner: { js: "// Generated by Tools/Localization/build.mjs. Do not edit.\n// Includes intl-messageformat and FormatJS dependencies (BSD-3-Clause / MIT); see haven-localization-NOTICES.txt." },
});
await mkdir(path.dirname(destination), { recursive: true });
await writeFile(destination, result.outputFiles[0].contents);
await copyFile(path.join(here, "THIRD_PARTY_NOTICES.md"), path.join(path.dirname(destination), "haven-localization-NOTICES.txt"));
console.log(`${destination}: ${result.outputFiles[0].contents.length} bytes`);
